version: '3.8'
services:
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
