version: '3.8'
services:
  app:
    container_name: task_manager_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/task_manager_db

  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
