version: '3.8'
services:
  api:
    container_name: nestjs_api
    image: node:latest
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/task_manager_db
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./:/app

  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
